export const zhTextMap: Record<string, string> = {
  Dashboard: '仪表盘',
  Farms: '农场',
  'Crops & Fields': '作物与田块',
  Livestock: '畜牧',
  Equipment: '设备',
  'Labor & Resources': '劳动力与资源',
  'Sales & Revenue': '销售与营收',
  'IoT Devices': 'IoT 设备',
  Irrigation: '灌溉',
  Weather: '天气',
  'Reports & Analytics': '报表与分析',
  'Tasks & Alerts': '任务与告警',
  Settings: '设置',

  active: '活跃',
  inactive: '停用',
  'on-leave': '休假中',
  pending: '待处理',
  'in-progress': '进行中',
  completed: '已完成',
  overdue: '已逾期',
  resolved: '已解决',
  operational: '正常运行',
  maintenance: '维护中',
  'out-of-service': '停用',
  retired: '已退役',
  online: '在线',
  offline: '离线',
  warning: '预警',
  critical: '严重',
  info: '信息',
  optimal: '最佳',
  'low-moisture': '墒情偏低',
  'low-battery': '电量低',
  scheduled: '已排程',
  idle: '空闲',
  paid: '已付款',
  on: '开启',
  off: '关闭',

  'Field A': 'A 地块',
  'Field B': 'B 地块',
  'Field C': 'C 地块',
  'Field D': 'D 地块',
  'Field E': 'E 地块',
  'Field A - Zone 1': 'A 地块 - 1 区',
  'Field A - Zone 2': 'A 地块 - 2 区',
  'Field B - Zone 1': 'B 地块 - 1 区',
  'Field B - Zone 2': 'B 地块 - 2 区',
  'Field C - Cotton': 'C 地块 - 棉花',
  'Field A - Central': 'A 地块 - 中央区',
  'Field A - North': 'A 地块 - 北区',
  'Field A - South': 'A 地块 - 南区',
  'Barn A': 'A 畜舍',
  'Barn B': 'B 畜舍',
  'Greenhouse 1': '1 号温室',
  'Greenhouse 2': '2 号温室',
  'Pasture A': 'A 牧场',
  'Pasture B': 'B 牧场',
  'Equipment Bay': '设备间',
  'Service Bay': '检修间',
  'Repair Shop': '维修车间',
  'Main Office': '主办公室',
  'Pump Station 3': '3 号泵站',
  'Water Tank B': 'B 水箱',
  'Field Storage': '田间仓库',
  'Greenhouse Area': '温室区',
  'California, USA': '美国加利福尼亚',
  'Texas, USA': '美国德克萨斯',
  'Colorado, USA': '美国科罗拉多',
  'Nebraska, USA': '美国内布拉斯加',
  'Virginia, USA': '美国弗吉尼亚',

  high: '高',
  medium: '中',
  low: '低',
  excellent: '优秀',
  good: '良好',
  fair: '一般',
  poor: '较差',
  Healthy: '健康',
  Sick: '生病',
  Good: '良好',
  Excellent: '优秀',
  Fair: '一般',
  High: '高',
  Medium: '中',
  Low: '低',
  'Up to date': '已更新',
  'Due soon': '即将到期',

  Corn: '玉米',
  'Sweet Corn': '甜玉米',
  Wheat: '小麦',
  'Winter Wheat': '冬小麦',
  'Non-GMO': '非转基因',
  Soybeans: '大豆',
  Cotton: '棉花',
  Barley: '大麦',
  Rice: '水稻',
  Tomatoes: '番茄',
  Potatoes: '土豆',
  Lettuce: '生菜',
  Carrots: '胡萝卜',
  'Organic Vegetables': '有机蔬菜',
  Herbs: '香草',
  Sugarcane: '甘蔗',
  Maize: '玉米',

  Cattle: '牛',
  Sheep: '羊',
  Chicken: '鸡',
  Holstein: '荷斯坦',
  Merino: '美利奴',
  'Rhode Island Red': '罗德岛红',

  Tractor: '拖拉机',
  'Combine Harvester': '联合收割机',
  Planter: '播种机',
  Cultivator: '中耕机',
  Mower: '割草机',
  Spreader: '撒布机',
  Sprayer: '喷雾机',
  'Utility Tractor': '多用途拖拉机',
  'Utility Vehicle': '多用途车辆',
  Loader: '装载机',
  'Disc Harrow': '圆盘耙',
  Baler: '打捆机',
  Other: '其他',
  'Heavy Machinery': '重型机械',
  'Medium Machinery': '中型机械',
  'Light Equipment': '轻型设备',
  'Hand Tools': '手持工具',
  Implements: '农具',
  'Utility Vehicles': '多用途车辆',

  'Farm Worker': '农场工人',
  'Equipment Operator': '设备操作员',
  'Livestock Manager': '畜牧经理',
  'Crop Specialist': '作物专家',
  'Irrigation Technician': '灌溉技术员',
  'General Laborer': '普通工人',
  'Farm Supervisor': '农场主管',
  'Maintenance Worker': '维护工人',
  'Harvest Worker': '收获工人',
  'Field Manager': '田块经理',
  'Crop Management': '作物管理',
  'Animal Care': '动物护理',
  'Irrigation Systems': '灌溉系统',
  'Equipment Maintenance': '设备维护',
  'Harvest Operations': '收获作业',
  'Multiple Tasks': '多任务',
  'Operations Management': '运营管理',
  'Organic Farming': '有机种植',
  'Precision Agriculture': '精准农业',
  'Tractor Operation': '拖拉机操作',
  'Animal Handling': '动物处理',
  'Crop Monitoring': '作物监测',
  Welding: '焊接',
  'Pesticide Application': '农药施用',
  'GPS/Precision Ag': 'GPS/精准农业',
  'Organic Practices': '有机实践',
  'Safety Protocols': '安全规程',
  'First Aid Certified': '急救认证',

  Cultivation: '耕作',
  Harvesting: '收获',
  'Feed Distribution': '饲料分发',
  'Crop Cultivation': '作物耕作',
  'Equipment Operation': '设备操作',
  'Livestock Care': '畜牧护理',
  'Irrigation Setup': '灌溉设置',
  'Field Preparation': '田块准备',
  'Fence Repair': '围栏维修',
  'General Labor': '普通劳务',
  irrigation: '灌溉',
  livestock: '畜牧',
  testing: '检测',
  monitoring: '监测',

  'Soil Moisture': '土壤湿度',
  'Weather Monitor': '天气监测',
  Humidity: '湿度',
  Camera: '摄像头',
  Closed: '关闭',
  Recording: '录制中',
  Battery: '电池',
  Inspection: '巡检',
  Firmware: '固件',
  Due: '到期',
  Overdue: '逾期',
  Scheduled: '已排程',
  Repair: '维修',
  Emergency: '紧急',
  'Oil change and filter replacement': '更换机油和滤芯',
  'Hydraulic pump replacement': '更换液压泵',
  'Engine diagnostics and repair': '发动机诊断与维修',

  Sunny: '晴',
  Cloudy: '多云',
  'Partly Cloudy': '局部多云',
  Rain: '雨',
  Mon: '周一',
  Tue: '周二',
  Wed: '周三',
  Thu: '周四',
  Fri: '周五',
  Sat: '周六',
  Sun: '周日',
  Today: '今天',
  Tomorrow: '明天',
  Wednesday: '周三',
  Thursday: '周四',

  'Spot Sale': '现货销售',
  'Forward Contract': '远期合同',
  'Premium Contract': '优质合同',
  'Direct Sale': '直销',
  'Futures Contract': '期货合同',
  'Pool Contract': '联合销售合同',
  Premium: '优质',
  'Export Grade': '出口级',
  Standard: '标准',
  Feed: '饲料级',
  'Organic Certified': '有机认证',
  'Food Grade': '食品级',
  Flowering: '开花期',
  Ripening: '成熟期',
  'Pod Development': '结荚期',
  'long-term': '长期',
  regular: '常规',
  new: '新',

  quintals: '公担',
  tonnes: '吨',
  kg: '千克',
  Jan: '1月',
  Feb: '2月',
  Mar: '3月',
  Apr: '4月',
  May: '5月',
  Jun: '6月',
  Jul: '7月',
  Aug: '8月',
};

export function zhText(value: unknown): string {
  if (typeof value !== 'string') return String(value);
  return zhTextMap[value] ?? value;
}

export function zhDate(value: string): string {
  return new Date(value).toLocaleDateString('zh-CN');
}

export function zhDateTime(value: string): string {
  return new Date(value).toLocaleString('zh-CN');
}
