/**
 * @name 企业供应链管理仪表盘
 *
 * 参考资料：
 * - /rules/prototype-development-guide.md
 */

import React, { useEffect } from 'react';
import './src/styles/index.css';
import App from './src/app/App';

const runtimeGlobal = globalThis as typeof globalThis & {
  React?: typeof React;
};

runtimeGlobal.React = React;

const textReplacements = ([
  ['Supply Chain Platform', '供应链平台'],
  ['Enterprise Platform', '企业平台'],
  ['Dashboard Overview', '仪表盘概览'],
  ['Real-time supply chain operations monitoring', '实时监控供应链运营状态'],
  ['Dashboard', '仪表盘'],
  ['Navigation', '导航'],
  ['Manage your operations', '管理运营工作'],
  ['Trips / Transports', '行程 / 运输'],
  ['Transports / Trips', '运输 / 行程'],
  ['Fleet Management', '车队管理'],
  ['Drivers', '司机'],
  ['Routes & Bookings', '路线与预约'],
  ['Revenue & Reports', '营收与报表'],
  ['Activity Logs', '活动日志'],
  ['Settings', '设置'],
  ['Overview and key metrics', '概览和关键指标'],
  ['Manage transportation orders', '管理运输订单'],
  ['Vehicle fleet and maintenance', '车辆车队与维护'],
  ['Driver management and assignments', '司机管理与派单'],
  ['Route optimization and customer bookings', '路线优化与客户预约'],
  ['Financial analytics and reporting', '财务分析与报表'],
  ['System logs and audit trail', '系统日志与审计记录'],
  ['System configuration and preferences', '系统配置与偏好'],
  ['Quick Actions', '快捷操作'],
  ['Optimize Routes', '优化路线'],
  ['View Analytics', '查看分析'],
  ['Check Alerts', '查看告警'],
  ['Generate Report', '生成报表'],
  ['System Status', '系统状态'],
  ['All systems operational', '所有系统运行正常'],
  ['Last update:', '最后更新：'],
  ['Last Update:', '最后更新：'],
  ['Search vehicles, trips, routes, drivers...', '搜索车辆、行程、路线、司机...'],
  ['Search vehicles, trips, drivers...', '搜索车辆、行程、司机...'],
  ['Search vehicles by name or ID...', '按车辆名称或 ID 搜索...'],
  ['Search drivers by name or ID...', '按司机姓名或 ID 搜索...'],
  ['Search by trip ID, customer, route...', '按行程 ID、客户、路线搜索...'],
  ['Search reports...', '搜索报表...'],
  ['Search logs...', '搜索日志...'],
  ['Search...', '搜索...'],
  ['Search', '搜索'],
  ['No results found.', '未找到结果。'],
  ['Quick Results', '快速结果'],
  ['Notifications', '通知'],
  ['Mark all read', '全部标为已读'],
  ['View all notifications', '查看全部通知'],
  ['Profile Settings', '个人资料设置'],
  ['Security', '安全'],
  ['Preferences', '偏好设置'],
  ['Sign Out', '退出登录'],
  ['Administrator', '管理员'],
  ['Fleet Manager', '车队经理'],

  ['Last 7 days', '最近 7 天'],
  ['Last 1 month', '最近 1 个月'],
  ['Last 3 months', '最近 3 个月'],
  ['Last 6 months', '最近 6 个月'],
  ['Last 1 year', '最近 1 年'],
  ['Year to date', '年初至今'],
  ['Select Time Period', '选择时间周期'],
  ['Choose a time range for dashboard data', '选择仪表盘数据的时间范围'],
  ['Past week data', '最近一周数据'],
  ['Past 30 days data', '最近 30 天数据'],
  ['Quarterly data', '季度数据'],
  ['Semi-annual data', '半年度数据'],
  ['Annual data', '年度数据'],
  ['Custom range', '自定义范围'],
  ['Select specific dates', '选择指定日期'],
  ['Filters', '筛选'],
  ['Advanced Filters', '高级筛选'],
  ['Apply Filters', '应用筛选'],
  ['Trip Status', '行程状态'],
  ['Select status', '选择状态'],
  ['All Statuses', '全部状态'],
  ['Vehicle Type', '车辆类型'],
  ['Select vehicle type', '选择车辆类型'],
  ['All Types', '全部类型'],
  ['Priority', '优先级'],
  ['Select priority', '选择优先级'],
  ['All Priorities', '全部优先级'],
  ['Revenue Range ($)', '营收范围（$）'],
  ['Distance Range (miles)', '距离范围（英里）'],
  ['Include Trip Types', '包含行程类型'],
  ['Completed Trips', '已完成行程'],
  ['Scheduled Trips', '已排期行程'],
  ['Reset', '重置'],
  ['Min', '最小'],
  ['Max', '最大'],
  ['Refresh', '刷新'],
  ['Refreshing...', '刷新中...'],
  ['Exporting...', '导出中...'],
  ['Export Logs', '导出日志'],
  ['Export Config', '导出配置'],
  ['Export Report', '导出报表'],
  ['Create Trip', '新建行程'],
  ['View All', '查看全部'],
  ['View Details', '查看详情'],
  ['View', '查看'],
  ['Edit', '编辑'],
  ['Delete', '删除'],
  ['Actions', '操作'],
  ['Cancel', '取消'],
  ['Close', '关闭'],
  ['Save', '保存'],
  ['Save Changes', '保存更改'],
  ['Save Draft', '保存草稿'],
  ['Previous', '上一步'],
  ['Next', '下一步'],
  ['Download', '下载'],
  ['Upload', '上传'],
  ['Generated Report', '已生成报表'],
  ["Today\\'s Revenue", '今日营收'],
  ["Today\\'s 营收", '今日营收'],
  ['Transports & Trips', '运输与行程'],
  ['Manage and track all transportation activities', '管理并追踪所有运输活动'],
  ['Completed Today', '今日已完成'],
  ['All Trips', '全部行程'],
  ['Trip ID', '行程 ID'],
  ['Route', '路线'],
  ['Vehicle', '车辆'],
  ['Driver', '司机'],
  ['Status', '状态'],
  ['Overview', '概览'],
  ['Timeline', '时间线'],
  ['Duration', '耗时'],
  ['Route Details', '路线详情'],
  ['Trip Information', '行程信息'],
  ['Manage vehicles, documents, and maintenance schedules', '管理车辆、证件和维护计划'],
  ['Add New Vehicle', '新增车辆'],
  ['Make & Model', '品牌与型号'],
  ['Fuel Level', '燃油余量'],
  ['Total Mileage', '总里程'],
  ['Next Maintenance', '下次维护'],
  ['Driver Management', '司机管理'],
  ['Drivers Management', '司机管理'],
  ['Manage driver profiles, performance, and assignments', '管理司机档案、表现和派单'],
  ['Add New Driver', '新增司机'],
  ['years experience', '年经验'],
  ['License & Certification', '执照与认证'],
  ['Quick Stats', '快速统计'],
  ['Total Trips', '总行程'],
  ['Earnings', '收入'],
  ['Rating', '评分'],
  ['Routes Management', '路线管理'],
  ['Route Management', '路线管理'],
  ['User Management', '用户管理'],
  ['Vehicle Maintenance', '车辆维护'],
  ['Manage routes, optimize paths, and handle customer bookings', '管理路线、优化路径并处理客户预约'],
  ['New Route', '新增路线'],
  ['Active Routes', '活跃路线'],
  ['Route Efficiency', '路线效率'],
  ['Booking Revenue', '预约营收'],
  ['Route Optimization', '路线优化'],
  ['Route Network', '路线网络'],
  ['Route Path', '路线'],
  ['Origin', '起点'],
  ['Destination', '终点'],
  ['Frequency', '频率'],
  ['Pricing Structure', '计价结构'],
  ['Est. Time', '预计时间'],
  ['Avg Revenue', '平均营收'],
  ['Financial analytics, performance metrics, and custom reports', '财务分析、绩效指标和自定义报表'],
  ['Total Revenue', '总营收'],
  ['Avg per Trip', '平均每单'],
  ['Profit Margin', '利润率'],
  ['Target Progress', '目标进度'],
  ['Revenue Overview', '营收概览'],
  ['Detailed Analysis', '详细分析'],
  ['Custom Reports', '自定义报表'],
  ['Forecasting', '预测'],
  ['Revenue by Transport Modes', '按运输方式统计营收'],
  ['Revenue by Transport Mode', '按运输方式统计营收'],
  ['Top Performing Routes', '表现最佳路线'],
  ['Revenue Trend - Last 12 Months', '最近 12 个月营收趋势'],
  ['Monitor system activities and user actions', '监控系统活动和用户操作'],
  ['Auto-refresh ON', '自动刷新开启'],
  ['Auto-refresh OFF', '自动刷新关闭'],
  ['Total Events', '事件总数'],
  ['System Events', '系统事件'],
  ['Security Logs', '安全日志'],
  ['All Categories', '全部类别'],
  ['All Status', '全部状态'],
  ['Timestamp', '时间戳'],
  ['User', '用户'],
  ['Action', '操作'],
  ['Category', '类别'],
  ['Details', '详情'],
  ['System Settings', '系统设置'],
  ['Configure system preferences, manage users, and monitor security', '配置系统偏好、管理用户并监控安全'],
  ['System Configuration', '系统配置'],
  ['General', '通用'],
  ['Users', '用户'],
  ['Notifications', '通知'],
  ['Integrations', '集成'],
  ['Audit Logs', '审计日志'],
  ['Company Name', '公司名称'],
  ['Timezone', '时区'],
  ['System Language', '系统语言'],
  ['Date Format', '日期格式'],
  ['Currency', '货币'],
  ['Appearance & Branding', '外观与品牌'],
  ['Theme Selection', '主题选择'],
  ['Light Mode', '浅色模式'],
  ['Dark Mode', '深色模式'],
  ['Company Logo', '公司 Logo'],
  ['Color Scheme', '配色方案'],
  ['Upload company logo', '上传公司 Logo'],
  ['PNG, JPG up to 2MB', 'PNG、JPG，最大 2MB'],
  ['System Version', '系统版本'],
  ['Database Size', '数据库大小'],
  ['Active Users', '活跃用户'],
  ['Last Backup', '上次备份'],
  ['Documents', '文档'],
  ['History', '历史'],
  ['Year:', '年份：'],
  ['Engine:', '发动机：'],
  ['Transmission:', '变速箱：'],
  ['Capacity:', '载重：'],
  ['License:', '执照：'],
  ['Expiry:', '到期日：'],
  ['Medical Cert:', '体检证明：'],
  ['Join Date:', '加入日期：'],
  ['Emergency Contact:', '紧急联系人：'],
  ['Eastern Time (ET)', '东部时间（ET）'],
  ['English', '英语'],

  ['Active Fleet', '活跃车队'],
  ['Active Trips', '进行中行程'],
  ['Monthly Revenue', '月度营收'],
  ['Available Drivers', '可用司机'],
  ['Pending Bookings', '待处理预约'],
  ['Fuel Efficiency', '燃油效率'],
  ['On-Time Rate', '准时率'],
  ['Maintenance Alerts', '维护提醒'],
  ['vehicles operational', '车辆运行中'],
  ['in progress now', '当前执行中'],
  ['vs last month', '较上月'],
  ['ready for dispatch', '可立即调度'],
  ['awaiting confirmation', '等待确认'],
  ['fleet average', '车队平均值'],
  ['delivery performance', '交付表现'],
  ['requiring attention', '需要关注'],
  ['Change', '变化'],
  ['Upcoming Trips', '即将出发的行程'],
  ['Performance Metrics', '绩效指标'],
  ['Revenue & Performance Trends', '营收与绩效趋势'],
  ['Transport Modes', '运输方式'],
  ['Revenue', '营收'],
  ['Profit', '利润'],
  ['Road Transport', '公路运输'],
  ['Air Transport', '航空运输'],
  ['Sea Transport', '海运运输'],
  ['Rail Transport', '铁路运输'],
  ['On-Time Delivery', '准时交付率'],
  ['Vehicle Utilization', '车辆利用率'],
  ['Customer Satisfaction', '客户满意度'],
  ['Current', '当前'],
  ['Target:', '目标：'],
  ['Target', '目标'],
  ['Active Vehicles', '活跃车辆'],
  ['Avg Delivery Time', '平均交付时长'],
  ['Avg Response Time', '平均响应时间'],
  ['Daily Target', '每日目标'],
  ["Today's Revenue", '今日营收'],
  ['Maintenance Due', '待维护'],
  ['Fleet Size', '车队规模'],
  ['Available Now', '当前可用'],
  ['Awaiting Confirm', '等待确认'],
  ['Requires Attention', '需要关注'],
  ['Success Rate', '成功率'],
  ['This Month', '本月'],
  ['Performance', '表现'],
  ['Fleet Average', '车队平均值'],
  ['In Progress', '进行中'],
  ['Peak Hours', '高峰时段'],
  ['Off Hours', '非高峰时段'],
  ['Business hours - full fleet active', '工作时段，全车队运行'],
  ['Reduced operations', '低频运营'],
  ['Weekend schedule', '周末排班'],
  ['Active deliveries', '活跃配送'],
  ['Real-time', '实时'],
  ['Day Total', '当日合计'],
  ['Accumulating...', '累计中...'],
  ['Target exceeded', '已超过目标'],
  ['Full staff', '全员在岗'],
  ['Night shift', '夜班'],
  ['Peak demand', '高峰需求'],
  ['Reduced urgency', '紧急度下降'],
  ['Optimized routes active', '已启用路线优化'],
  ['Rush hour traffic', '高峰交通'],
  ['Clear roads', '路况顺畅'],
  ['On track', '进度正常'],
  ['Ahead of schedule', '进度提前'],
  ['Pickup ETA', '提货 ETA'],
  ['Progress', '进度'],
  ['Urgent Deliveries', '紧急交付'],
  ['Real-time Trips', '实时行程'],

  ['Live Fleet Tracking - Google Maps', '实时车队追踪 - Google Maps'],
  ['Exit Fullscreen', '退出全屏'],
  ['Fullscreen', '全屏'],
  ['All Vehicles', '全部车辆'],
  ['Active Only', '仅活跃'],
  ['Vehicle Types', '车辆类型'],
  ['Driver:', '司机：'],
  ['Location:', '位置：'],
  ['Speed:', '速度：'],
  ['Fuel:', '燃油：'],
  ['ETA:', '预计到达：'],
  ['Track Route', '追踪路线'],
  ['Live Tracking Active', '实时追踪已开启'],
  ['vehicles in transit', '辆运输中'],
  ['Satellite', '卫星'],
  ['Terrain', '地形'],
  ['Active Vehicles', '活跃车辆'],
  ['Initializing Google Maps...', '正在初始化 Google Maps...'],

  ['Create New Trip', '新建行程'],
  ['Trip Details', '行程详情'],
  ['Vehicle Information', '车辆信息'],
  ['Contact Information', '联系信息'],
  ['System Information', '系统信息'],
  ['Customer', '客户'],
  ['Select customer', '选择客户'],
  ['Priority Level', '优先级'],
  ['Low Priority', '低优先级'],
  ['Medium Priority', '中优先级'],
  ['High Priority', '高优先级'],
  ['Origin Address', '起点地址'],
  ['Destination Address', '目的地地址'],
  ['Enter pickup location', '输入提货地点'],
  ['Enter delivery location', '输入送达地点'],
  ['Distance', '距离'],
  ['Estimated Duration', '预计耗时'],
  ['Transport Mode', '运输方式'],
  ['Select mode', '选择方式'],
  ['Pickup Date', '提货日期'],
  ['Delivery Date', '送达日期'],
  ['Select pickup date', '选择提货日期'],
  ['Select delivery date', '选择送达日期'],
  ['Cargo Information', '货物信息'],
  ['Cargo Type', '货物类型'],
  ['Weight', '重量'],
  ['Dimensions', '尺寸'],
  ['Cargo Value', '货值'],
  ['Special Requirements', '特殊要求'],
  ['Temperature Control', '温控'],
  ['Fragile Handling', '易碎品处理'],
  ['Hazardous Materials', '危险品'],
  ['Express Delivery', '加急配送'],
  ['White Glove Service', '高端交付服务'],
  ['Insurance Required', '需要保险'],
  ['Assignment', '分配'],
  ['Assigned Driver', '指派司机'],
  ['Assigned Vehicle', '指派车辆'],
  ['Pricing', '计价'],
  ['Base Rate', '基础费率'],
  ['Fuel Surcharge', '燃油附加费'],
  ['Additional Fees', '附加费用'],
  ['Total Estimate', '预估总额'],
  ['Calculate Estimate', '计算预估'],
  ['Creating...', '创建中...'],
  ['Trip created successfully! Trip ID:', '行程创建成功！行程 ID：'],
  ['Add any special notes or requirements...', '补充特殊说明或要求...'],

  ['Vehicle Maintenance Due', '车辆维护即将到期'],
  ['Trip Completed', '行程已完成'],
  ['New Booking Request', '新的预约请求'],
  ['Route Optimization Available', '可用路线优化'],
  ['TRK-001 scheduled maintenance in 2 days', 'TRK-001 将在 2 天后进行计划维护'],
  ['TR-2024-089 delivered successfully to Boston', 'TR-2024-089 已成功送达 Boston'],
  ['Acme Corp requested shipment for Jan 20', 'Acme Corp 请求 1 月 20 日发货'],
  ['NY-Boston route can be optimized by 8%', 'NY-Boston 路线可优化 8%'],
  ['5 min ago', '5 分钟前'],
  ['15 min ago', '15 分钟前'],
  ['1 hour ago', '1 小时前'],
  ['2 hours ago', '2 小时前'],
  ['Truck TRK-001', '卡车 TRK-001'],
  ['Volvo VNL 860 - Active', 'Volvo VNL 860 - 活跃'],
  ['Professional Driver - Available', '专业司机 - 可用'],
  ['Trip TR-2024-001', '行程 TR-2024-001'],
  ['NY to Boston - In Transit', 'NY 至 Boston - 运输中'],
  ['Primary Route - 215 miles', '主路线 - 215 英里'],
  ['Premium Customer - Active', '高级客户 - 活跃'],

  ['Active', '活跃'],
  ['Inactive', '未启用'],
  ['Available', '可用'],
  ['In Transit', '运输中'],
  ['Loading', '装载中'],
  ['Delivered', '已送达'],
  ['Maintenance', '维护中'],
  ['Completed', '已完成'],
  ['Confirmed', '已确认'],
  ['Pending', '待处理'],
  ['Cancelled', '已取消'],
  ['Scheduled', '已排期'],
  ['Ready', '就绪'],
  ['High', '高'],
  ['Medium', '中'],
  ['Low', '低'],
  ['Urgent', '紧急'],
  ['Normal', '普通'],
  ['Not Started', '未开始'],
  ['En Route', '途中'],
  ['On Trip', '行程中'],
  ['Off Duty', '离岗'],
  ['On Duty', '在岗'],
  ['Suspended', '已停用'],
  ['Enabled', '已启用'],
  ['Alert Generated', '告警已生成'],
  ['Failed', '失败'],
  ['Processing', '处理中'],
  ['Updated', '已更新'],
  ['Created', '已创建'],
  ['Started', '已开始'],
  ['Truck', '卡车'],
  ['Van', '厢式货车'],
  ['Aircraft', '飞机'],
  ['Electronics', '电子产品'],
  ['Medical Supplies', '医疗物资'],
  ['Fresh Produce', '生鲜农产品'],
  ['Consumer Goods', '消费品'],
  ['Machinery', '机械设备'],
] as Array<[string, string]>).sort((a, b) => b[0].length - a[0].length);

const wordReplacements: Array<[RegExp, string]> = [
  [/\bRoad\b/g, '公路'],
  [/\bAir\b/g, '航空'],
  [/\bSea\b/g, '海运'],
  [/\bMap\b/g, '地图'],
  [/\bAll\b/g, '全部'],
  [/\bExport\b/g, '导出'],
  [/\bGenerate\b/g, '生成'],
  [/\bGenerated\b/g, '已生成'],
  [/\bSuccess\b/g, '成功'],
  [/\bSuccessful\b/g, '成功'],
  [/\bWarning\b/g, '警告'],
  [/\bWarnings\b/g, '警告'],
  [/\bError\b/g, '错误'],
  [/\bErrors\b/g, '错误'],
  [/\bInfo\b/g, '信息'],
  [/\bInformation\b/g, '信息'],
  [/\byears experience\b/g, '年经验'],
  [/\btrips\b/g, '趟'],
  [/\bAvg\b/g, '平均'],
  [/\bMargin\b/g, '利润率'],
  [/\bEfficiency\b/g, '效率'],
  [/\bPath\b/g, '路径'],
  [/\bMode\b/g, '方式'],
  [/\bBookings\b/g, '预约'],
  [/\bDaily\b/g, '每日'],
  [/\bSeasonal\b/g, '季节性'],
  [/\bInternational Waters\b/g, '国际水域'],
  [/\bJan\b/g, '1月'],
  [/\bFeb\b/g, '2月'],
  [/\bMar\b/g, '3月'],
  [/\bApr\b/g, '4月'],
  [/\bMay\b/g, '5月'],
  [/\bJun\b/g, '6月'],
  [/\bJul\b/g, '7月'],
  [/\bAug\b/g, '8月'],
  [/\bSep\b/g, '9月'],
  [/\bOct\b/g, '10月'],
  [/\bNov\b/g, '11月'],
  [/\bDec\b/g, '12月'],
];

function localizeText(value: string) {
  const phraseLocalized = textReplacements.reduce(
    (result, [source, target]) => result.split(source).join(target),
    value,
  );

  return wordReplacements.reduce(
    (result, [source, target]) => result.replace(source, target),
    phraseLocalized,
  );
}

function localizeNodeText(root: ParentNode) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const textNodes: Text[] = [];

  while (walker.nextNode()) {
    textNodes.push(walker.currentNode as Text);
  }

  for (const node of textNodes) {
    const nextValue = localizeText(node.nodeValue ?? '');
    if (nextValue !== node.nodeValue) {
      node.nodeValue = nextValue;
    }
  }
}

function localizeAttributes(root: ParentNode) {
  const elements = Array.from(root.querySelectorAll<HTMLElement>('[placeholder], [title], [aria-label]'));

  for (const element of elements) {
    for (const attribute of ['placeholder', 'title', 'aria-label']) {
      const value = element.getAttribute(attribute);
      if (!value) continue;

      const nextValue = localizeText(value);
      if (nextValue !== value) {
        element.setAttribute(attribute, nextValue);
      }
    }
  }
}

function useVisibleTextLocalization() {
  useEffect(() => {
    const root = document.getElementById('root');
    if (!root) return;

    const localize = () => {
      localizeNodeText(root);
      localizeAttributes(root);
    };

    localize();

    const observer = new MutationObserver(localize);
    observer.observe(root, {
      attributes: true,
      attributeFilter: ['placeholder', 'title', 'aria-label'],
      characterData: true,
      childList: true,
      subtree: true,
    });

    return () => observer.disconnect();
  }, []);
}

export default function EnterpriseSupplyChainManagementDashboard() {
  useVisibleTextLocalization();

  return <App />;
}
